// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIqmpo7Dc2KXIym1o8KlFo9kFhjA2z-NI',
    appId: '1:791425532916:web:d9e1831a0dd424ef5fafa1',
    messagingSenderId: '791425532916',
    projectId: 'voyage-eb19e',
    authDomain: 'voyage-eb19e.firebaseapp.com',
    storageBucket: 'voyage-eb19e.appspot.com',
    measurementId: 'G-R0J6FJZSP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDShjkVz-rOgPGVYhOPRSCP6FQp-lpnOkQ',
    appId: '1:791425532916:android:8f04909f8b73669a5fafa1',
    messagingSenderId: '791425532916',
    projectId: 'voyage-eb19e',
    storageBucket: 'voyage-eb19e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA4zrlN05uX5gx2zLAhn_iXgEyiBAdt5E',
    appId: '1:791425532916:ios:34f3a3f12bd0b74c5fafa1',
    messagingSenderId: '791425532916',
    projectId: 'voyage-eb19e',
    storageBucket: 'voyage-eb19e.appspot.com',
    iosClientId: '791425532916-kcn88mp552r2dr3digf540t91mbd3tjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.voyage',
  );
}
